/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controladores.factory.CFactory;
import controladores.factory.IActividad;
import controladores.factory.IRepartidor;
import controladores.factory.ITarjeta;
import entidades.Actividad;
import entidades.Repartidor;
import entidades.Tarjeta;
import javax.swing.JOptionPane;
import util.DatosIni;
import util.Formateador;
import util.MyComboBoxModel;
import util.Resultado;

/**
 *
 * @author Rosary
 */
public class FrmAsistencia extends javax.swing.JInternalFrame {

    private final IActividad cActividad;
    private final IRepartidor cRepartidor;
    private final ITarjeta cTarjeta;
    private final MyComboBoxModel cbmActividad = new MyComboBoxModel();
    private double valor;
    private Repartidor repartidor;
    private Tarjeta tarjeta;

    public FrmAsistencia() {
        initComponents();
        int bd = DatosIni.getBd().equals("MySql") ? CFactory.MYSQL : CFactory.ACCESS;
        cActividad = CFactory.getCFactory(bd).getCActividad();
        cRepartidor = CFactory.getCFactory(bd).getCRepartidor();
        cTarjeta = CFactory.getCFactory(bd).getCTarjeta();
        error.setVisible(false);
        lblRepartidor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalTarjetas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMontoPagado = new javax.swing.JTextField();
        txtColaborador = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotalAPagar = new javax.swing.JTextField();
        chkLibre = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        error = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMontoPagadoPorTarjeta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblRepartidor = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cboActividad = new javax.swing.JComboBox();
        chkLimpiar = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Asistencia de colaboradores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Núm tarjeta");

        txtNumTarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTarjetaActionPerformed(evt);
            }
        });
        txtNumTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTarjetaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total Tarjts.");

        txtTotalTarjetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalTarjetas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalTarjetasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalTarjetasKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Monto pagado");

        txtMontoPagado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMontoPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoPagadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoPagadoKeyTyped(evt);
            }
        });

        txtColaborador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtColaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColaboradorKeyTyped(evt);
            }
        });

        txtVuelto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Colaborador");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Vuelto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total a pagar");

        txtTotalAPagar.setEditable(false);
        txtTotalAPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        chkLibre.setBackground(new java.awt.Color(204, 204, 204));
        chkLibre.setText("Libre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nota");

        txtNota.setColumns(20);
        txtNota.setRows(5);
        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNotaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtNota);

        error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/error_war16x16.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Monto por Tarjeta");

        txtMontoPagadoPorTarjeta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMontoPagadoPorTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoPagadoPorTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoPagadoPorTarjetaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColaborador)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkLibre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(error)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoPagadoPorTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLibre)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMontoPagadoPorTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/education-languages.png"))); // NOI18N
        jLabel4.setText("Repartidor");

        lblRepartidor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRepartidor.setText("[REPARTIDOR]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblRepartidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cboActividad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboActividad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboActividadItemStateChanged(evt);
            }
        });

        chkLimpiar.setSelected(true);
        chkLimpiar.setText("Limpiar datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(cboActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(chkLimpiar))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(tarjeta==null||txtNumTarjeta.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Indique tarjeta", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }       
        double montoPagadoPorTarjeta;
        try {
            montoPagadoPorTarjeta = Double.parseDouble(txtMontoPagadoPorTarjeta.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Monto pagado por tarjeta inválido", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        tarjeta.setColaborador(txtColaborador.getText());
        tarjeta.setEstado(chkLibre.isSelected() ? "LIBRE" : "ASISTIDO");
        tarjeta.setMontoPagado(montoPagadoPorTarjeta);
        tarjeta.setNota(txtNota.getText());

        Resultado resultado = cTarjeta.actualizar(tarjeta);
        if (resultado.isCorrecto()) {
            JOptionPane.showMessageDialog(this, "Tarjeta asistida exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            if(chkLimpiar.isSelected()){
                limpiarCampos();
            }
        } else {
            Formateador.mostrarMensajeError(resultado, this);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    
    
    private void limpiarCampos() {
        tarjeta = null;
        repartidor = null;
        lblRepartidor.setText("");
        txtColaborador.setText("");
        txtMontoPagado.setText("");
        txtMontoPagadoPorTarjeta.setText("");
        txtNota.setText("");
        txtNumTarjeta.setText("");
        txtTotalAPagar.setText("");
        txtTotalTarjetas.setText("");
        txtVuelto.setText("");
        chkLibre.setSelected(false);
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNumTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTarjetaKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==8){//si está borrando
            btnGuardar.setEnabled(true);
            error.setVisible(false);
        }
 
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        Formateador.setMaxTamanio(txtNumTarjeta, 6, evt);

    }//GEN-LAST:event_txtNumTarjetaKeyTyped

    private void txtNumTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTarjetaKeyReleased
        // TODO add your handling code here:
        if(cboActividad.getItemCount()==0){
            JOptionPane.showMessageDialog(this, "Registre actividad primero", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtNumTarjeta.getText().isEmpty()) {
            lblRepartidor.setText("");
        }else{
            String numTarjeta = getNumTarjetaFormateada(Integer.parseInt(txtNumTarjeta.getText()));
            int idActividad = cbmActividad.getSelectedCodigo();
            buscarNumTarjeta(numTarjeta,idActividad);
        }
        
    }//GEN-LAST:event_txtNumTarjetaKeyReleased

    private void buscarNumTarjeta(String numTarjeta,int idActividad){
        
        tarjeta = cTarjeta.buscar(numTarjeta,idActividad);
        if (tarjeta == null) {
            lblRepartidor.setText("No encontrado");
        } else {
            if (tarjeta.getEstado() != null
                    && (tarjeta.getEstado().equals("ASISTIDO")
                    || tarjeta.getEstado().equals("LIBRE"))) {
                error.setVisible(true);
                error.setToolTipText("Tarjeta asistida");
                btnGuardar.setEnabled(false);
            } else {
                error.setVisible(false);
                btnGuardar.setEnabled(true);
            }
            int idRepartidor = tarjeta.getId_repartidor();
            repartidor = cRepartidor.buscar(idRepartidor);
            lblRepartidor.setText(repartidor.getNombre());
            txtMontoPagadoPorTarjeta.setText("" + valor);
        }
    }
    
    private void txtTotalTarjetasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalTarjetasKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalTarjetasKeyTyped

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        cargarActividad();
        if (cboActividad.getItemCount() != 0) {
            int idActividad = cbmActividad.getSelectedCodigo();
            Actividad actividad = cActividad.buscar(idActividad);
            valor = actividad.getValor();
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cboActividadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboActividadItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cboActividadItemStateChanged

    private void txtMontoPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoPagadoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        Formateador.setMaxTamanio(txtMontoPagado, 10, evt);
    }//GEN-LAST:event_txtMontoPagadoKeyTyped

    private void txtMontoPagadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoPagadoKeyReleased
        // TODO add your handling code here:
        if (txtMontoPagado.getText().isEmpty()
                || txtTotalAPagar.getText().isEmpty()) {
            txtVuelto.setText("");
            return;
        }

        double totalAPagar = Double.parseDouble(txtTotalAPagar.getText());
        double montoPagado = Double.parseDouble(txtMontoPagado.getText());

        if (montoPagado >= totalAPagar) {
            double vuelto = montoPagado - totalAPagar;
            txtVuelto.setText("" + vuelto);

        } else if (montoPagado < totalAPagar) {
            txtVuelto.setText("0.0");
        }

    }//GEN-LAST:event_txtMontoPagadoKeyReleased

    private void txtTotalTarjetasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalTarjetasKeyReleased
        // TODO add your handling code here:
        if (txtTotalTarjetas.getText().isEmpty()) {
            txtTotalAPagar.setText("");
            return;
        }

        int totalTarjetas = Integer.parseInt(txtTotalTarjetas.getText());
        double totalAPagar = totalTarjetas * valor;
        txtTotalAPagar.setText("" + totalAPagar);
        txtMontoPagadoPorTarjeta.setText("" + valor);

        if (txtMontoPagado.getText().isEmpty()) {
            txtVuelto.setText("");
            return;
        }

        double montoPagado = Double.parseDouble(txtMontoPagado.getText());

        if (montoPagado >= totalAPagar) {
            double vuelto = montoPagado - totalAPagar;
            txtVuelto.setText("" + vuelto);

        } else if (montoPagado < totalAPagar) {
            txtVuelto.setText("0.0");
        }
    }//GEN-LAST:event_txtTotalTarjetasKeyReleased

    private void txtMontoPagadoPorTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoPagadoPorTarjetaKeyReleased
        // TODO add your handling code here:
        if (txtMontoPagado.getText().isEmpty()
                || txtTotalAPagar.getText().isEmpty()) {
            txtVuelto.setText("");
        }
    }//GEN-LAST:event_txtMontoPagadoPorTarjetaKeyReleased

    private void txtMontoPagadoPorTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoPagadoPorTarjetaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        Formateador.setMaxTamanio(txtMontoPagado, 10, evt);
    }//GEN-LAST:event_txtMontoPagadoPorTarjetaKeyTyped

    private void txtNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyTyped
        // TODO add your handling code here:
        Formateador.setMaxTamanio(txtNota, 45, evt);
    }//GEN-LAST:event_txtNotaKeyTyped

    private void txtColaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColaboradorKeyTyped
        // TODO add your handling code here:
        Formateador.setMaxTamanio(txtColaborador, 20, evt);
    }//GEN-LAST:event_txtColaboradorKeyTyped

    private void txtNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTarjetaActionPerformed
        // TODO add your handling code here:
        btnGuardar.doClick();
    }//GEN-LAST:event_txtNumTarjetaActionPerformed

    private void cargarActividad() {
        Resultado resultado = cActividad.listar();
        if (resultado.isCorrecto()) {
            cbmActividad.setData(resultado.getItemsCombo());
            cboActividad.setModel(cbmActividad);
            if (cboActividad.getItemCount() != 0) {
                cboActividad.setSelectedIndex(0);
            }
        } else {
            Formateador.mostrarMensajeError(resultado, this);
        }
    }

    private String getNumTarjetaFormateada(int num) {
        String numFormateado = "";
        if (num < 10) {
            numFormateado = "00000" + num;
        } else if (num < 100) {
            numFormateado = "0000" + num;
        } else if (num < 1000) {
            numFormateado = "000" + num;
        } else if (num < 10000) {
            numFormateado = "00" + num;
        } else if (num < 100000) {
            numFormateado = "0" + num;
        } else {
            numFormateado = "" + num;
        }
        return numFormateado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboActividad;
    private javax.swing.JCheckBox chkLibre;
    private javax.swing.JCheckBox chkLimpiar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRepartidor;
    private javax.swing.JTextField txtColaborador;
    private javax.swing.JTextField txtMontoPagado;
    private javax.swing.JTextField txtMontoPagadoPorTarjeta;
    private javax.swing.JTextArea txtNota;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JTextField txtTotalAPagar;
    private javax.swing.JTextField txtTotalTarjetas;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
