/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.edisoncor.gui.util.WindowDragger;
import util.DatosIni;
import util.Formateador;

/**
 *
 * @author Rosary
 */
public class WinControlTarjetas extends javax.swing.JFrame {

    private FrmActividades frmActividades;
    private FrmAsignarTarjetas frmAsignarTarjetas;
    private FrmAsistencia frmAsistencia;
    private FrmRepartidores frmRepartidores;
    private FrmReportes frmReportes;
    
    public WinControlTarjetas() {
        new DatosIni();
        initComponents();
        setLocationRelativeTo(null);
        WindowsUtil.makeWindowsOpacity(this, .9f);
        WindowsUtil.makeWindowsShape(this, panelLindo.getShape());
        new WindowDragger(this, panelLindo);
        barraTitulo.addCloseAction(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowsUtil = new org.edisoncor.gui.util.WindowsUtil();
        panelLindo = new org.edisoncor.gui.panel.PanelNice();
        barraTitulo = new org.edisoncor.gui.varios.TitleBar();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jPanel1 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        btnActividades = new javax.swing.JButton();
        btnRepartidores = new javax.swing.JButton();
        btnAsignarTarjetas = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        barraTitulo.setTitulo("Sistema de Gestión de Actividad Económica ");
        panelLindo.add(barraTitulo, java.awt.BorderLayout.PAGE_START);

        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        btnActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chicken_of_the_vnc.png"))); // NOI18N
        btnActividades.setText("Actividades");
        btnActividades.setFocusable(false);
        btnActividades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActividades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesActionPerformed(evt);
            }
        });
        jToolBar4.add(btnActividades);

        btnRepartidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/education-languages.png"))); // NOI18N
        btnRepartidores.setText("Repartidores");
        btnRepartidores.setFocusable(false);
        btnRepartidores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRepartidores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepartidoresActionPerformed(evt);
            }
        });
        jToolBar4.add(btnRepartidores);

        btnAsignarTarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mail-unread-4.png"))); // NOI18N
        btnAsignarTarjetas.setText("Asignar tarjetas");
        btnAsignarTarjetas.setFocusable(false);
        btnAsignarTarjetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignarTarjetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsignarTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTarjetasActionPerformed(evt);
            }
        });
        jToolBar4.add(btnAsignarTarjetas);

        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calendar_2.png"))); // NOI18N
        btnAsistencia.setText("Asistencia");
        btnAsistencia.setFocusable(false);
        btnAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });
        jToolBar4.add(btnAsistencia);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chart_Bar_Table.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jToolBar4.add(btnReportes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelNice1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        escritorio.setLayer(panelCurves1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        panelNice1.add(escritorio, java.awt.BorderLayout.CENTER);

        panelLindo.add(panelNice1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
        // TODO add your handling code here:
        if(frmActividades==null||frmActividades.isClosed()){
            frmActividades = new FrmActividades();    
            escritorio.add(frmActividades);
            Formateador.setLocationCenter(frmActividades, escritorio);
            frmActividades.setVisible(true);
            //y maximizarlo si está minimizado
        }else{
            frmActividades.toFront();
        }
    }//GEN-LAST:event_btnActividadesActionPerformed

    private void btnRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepartidoresActionPerformed
        // TODO add your handling code here:
        if(frmRepartidores==null||frmRepartidores.isClosed()){
            frmRepartidores = new FrmRepartidores();    
            escritorio.add(frmRepartidores);
            Formateador.setLocationCenter(frmRepartidores, escritorio);
            frmRepartidores.setVisible(true);
            //y maximizarlo si está minimizado
        }else{
            frmRepartidores.toFront();
        }
    }//GEN-LAST:event_btnRepartidoresActionPerformed

    private void btnAsignarTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTarjetasActionPerformed
        // TODO add your handling code here:
        if(frmAsignarTarjetas==null||frmAsignarTarjetas.isClosed()){
            frmAsignarTarjetas = new FrmAsignarTarjetas();    
            escritorio.add(frmAsignarTarjetas);
            Formateador.setLocationCenter(frmAsignarTarjetas, escritorio);
            frmAsignarTarjetas.setVisible(true);
            //y maximizarlo si está minimizado
        }else{
            frmAsignarTarjetas.toFront();
        }
    }//GEN-LAST:event_btnAsignarTarjetasActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        // TODO add your handling code here:
        if(frmAsistencia==null||frmAsistencia.isClosed()){
            frmAsistencia = new FrmAsistencia();    
            escritorio.add(frmAsistencia);
            Formateador.setLocationCenter(frmAsistencia, escritorio);
            frmAsistencia.setVisible(true);
            //y maximizarlo si está minimizado
        }else{
            frmAsignarTarjetas.toFront();
        }
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        if(frmReportes==null||frmReportes.isClosed()){
            frmReportes = new FrmReportes();    
            escritorio.add(frmReportes);
            Formateador.setLocationCenter(frmReportes, escritorio);
            frmReportes.setVisible(true);
            //y maximizarlo si está minimizado
        }else{
            frmReportes.toFront();
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinControlTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinControlTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinControlTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinControlTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinControlTarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.util.WindowsUtil WindowsUtil;
    private org.edisoncor.gui.varios.TitleBar barraTitulo;
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnAsignarTarjetas;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnRepartidores;
    private javax.swing.JButton btnReportes;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelLindo;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
